version: '3.8'
service:
  vprodb:
    context: ./Docker-files/db
  image: ssgaikwad/db
  container-name: vprodb
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=vprodbpass
  volume:
    - vprodbdata:/var/lib/mysql
  
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
    
  vpromq01:
    image: rabbitmq
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
    image: ssgaikwad/app
    container-name: vproapp
    ports:
      - "8080:8080"
    volume:
      - vproappdata:/usr/local/tomcat/webapps
    
  vproweb:
    build:
      context: ./Docker-files/web
    images: ssgaikwad/web
    container-name: vproweb
    ports:
      - "80:80"

volumes:
  vproappdata: {}
  vprodbdata: {}