
version: '3.8'
services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: ssgaikwad/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    Environment:
      - MYSQL_ROOT_PASSWORD:vprodbpass
    volume:
      - vprodbdata:/var/lib/mysql

  vprocache01:
    image: "memcached"
    ports:
      - "11211:11211"
  
  vpromq01:
    image: "rabbitmq"
    ports:
      - "5672:5672"

  vproapp:
    build: 
      context: ./Docker-files/app
    image: ssgaikwad/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volume:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build: 
      context: ./Docker-files/web
    image: ssgaikwad/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
  

