<<<<<<< HEAD
version: '3.8'
services:
  vprodb:
    build: 
      - context: ./Docker-files/db/
    images: ssgaikwad/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
      image: rabbitmq
      ports:
        - "15672:15672"
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
  
  vproapp:
    build:
      - context: ./Docker-files/app/
    images: ssgaikwad/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
  vproweb:
    build:
      - context: ./Docker-files/web/
    images: ssgaikwad/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

service:
  vprodbdata: {}
  vproappdata: {}
    
=======

>>>>>>> f6b982aa63a4563654dbffd025ba09140a7a507e
